### PR TITLE
Hammerhead Fixes

### LINKED ISSUE #152: [HAMMERHEAD] No bot pathing nodes.
## Reproduction: Unlock a medibot and enable the patrol mode

The medibots dont seem to have a path mapping yet (or a broken one) and every time you enable their patrol mode it immeadietly disables again, so they are unable to patrol the station.

### LINKED ISSUE #215: [Hammerhead] the warden's locker doesn't exist
the wardens locker kind of contains some useful/high risk items, including but not limited to

the security door remote (no, the HoS doesn't get one for some unknown reason)
the krav gloves (once again, the HoS doesn't get a pair for some unknown reason)
the compact combat shotgun
the warden's blue jacket (which looks c00m in all regards)

### LINKED ISSUE #221: [Hammerhead] Open Pipes on Distro and Scrubbers loops
Here's the locations as gotten from the **Check Pipes** debug verb:
Unconnected air supply pipe located at Central Port Maintenance **(95, 130, 2)**
Unconnected scrubbers pipe located at Central Port Maintenance **(95, 130, 2)**
Unconnected scrubbers pipe located at Fore Primary Hallway **(171, 108, 2)**
Unconnected air supply pipe located at Fore Primary Hallway **(171, 108, 2)**
Unconnected air supply pipe located at Fore Primary Hallway **(214, 108, 2)**
Unconnected pipe located at Port Primary Hallway **(206, 110, 2)**

### LINKED ISSUE #226: [HAMMERHEAD] Medical missing IV/bodybags
## Round ID:

62

## Testmerges:

N/A

## Reproduction:

N/A

There are no bodybags/IV drips available in medical

### PR DESCRIPTION
**Pull request by Shadow-Quill**
## About The Pull Request
- Adds bot pathing to the ship. Fixes #152.
- Adds warden's locker to their office. Fixes #215.
- Closes opened pipes. Fixes #221.
- Adds two body bag boxes and two IV drips to medical. Fixes #226.

Actually tested, too. (I'm looking at you, Vasily)

## Why It's Good For The Game

Closing issues, woo!

## Changelog
:cl:
add: Bot navigation nodes. Patrols will now function.
add: Warden's locker to their office.
add: IV drips and bodybag boxes to Medical.
fix: Fixed open-ended pipes.
/:cl:

### CODE REVIEW

**Comment by Vasily2013** [comment]
No actual listed fixes or changelog. PR not mapper approved.

**Comment by Shadow-Quill** [comment]
@Vasily2013 Read: I pressed enter while not in the text box, thus submitting the PR. Hush.

**Comment by Vasily2013** [comment]
Have you tested the bot pathing nodes to make sure they behave as expected?

**Comment by Shadow-Quill** [comment]
@Vasily2013 Yes, yes I have.

**Comment by Shadow-Quill** [comment]
I'll toss in one more issue fix in a minute.

**Comment by Vasily2013** [comment]
Cool, approved for test/full merge at maintainer's discretion.

**Comment by Kmc2000** [comment]
based

**Pull request merged**
