### PR TITLE
Codebase Superficial Cleanup

### PR DESCRIPTION
**Pull request by francinum**
Changes Travis badge to .com travis.
Disables Documentation generation (Need to get around to figuring it out, but for now it'll allow master to pass travis.
No changelog as this is not a gameserver change.

### CODE REVIEW

**Comment by Crossedfall** [comment]
Since it's a quick and easy change you might as well update the version of BYOND Travis uses in this PR too. Unless you're using an older version

https://github.com/DDMers/NSV13/blob/85463b6cd83d0c96033fd33c86542bc0b2654e27/Dockerfile#L1

**Comment by Kmc2000** [comment]
> Since it's a quick and easy change you might as well update the version of BYOND Travis uses in this PR too. Unless you're using an older version
> 
> https://github.com/DDMers/NSV13/blob/85463b6cd83d0c96033fd33c86542bc0b2654e27/Dockerfile#L1

Perhaps. What versions are properly stable?

**Comment by Crossedfall** [comment]
The latest version is properly stable (1488). I wouldn't upgrade to 513 yet, unless you've done the ground work to add compatability for that.

**Comment by francinum** [comment]
The server and TG both currently run `1484`

**Comment by Crossedfall** [comment]
@francinum tg is running the 1488 and the 513 beta.

**Pull request merged**
